package myEnums;

public enum Task {
    HUMANS_INTERACTION,
    PRINT_VIA_INTERFACE,
    TYPE_CONVERSION,
    STATIC_METHOD_FROM_INTERFACE,
    EXTENDS_INTERFACE,
    CALLBACK_MECHANISM,
    ENUM,
    OBJECT,
    TEST_REF,
    GENERICS,
    GENERALIZATION_CONSTRAINTS
}
